version: "3"
services:
    app:
        build: ./image
        image: tender-list
        container_name: tender-list
        environment:
            - TOKEN=${TOKEN}
            - TOKENLOG=${TOKENLOG}
        restart: unless-stopped
        volumes:
            - ./data:/data