version: '3'
services:
    app:
        build: image/
        image: ks_mindreaver3
        container_name: ks_mindreaver3
        restart: unless-stopped
        environment:
            - API_KEY=${API_KEY}
            - MONGODB=${MONGODB}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}