version: '3'
services:
    proxima_gallery:
        build: ./proxima_image
        image: proxima_twitter
        container_name: proxima_gallery
        restart: always
        environment:
            - TWITTER_TOKEN=${TWITTER_TOKEN}
            - SUB_TOKEN=${SUB_TOKEN}
            - WEBHOOK=${PROXIMA_GALLERY}
            - QUERY_STR=${GALLERY_QUERY}

    proxima_meme:
        image: proxima_twitter
        container_name: proxima_meme
        restart: always
        environment: 
            - TWITTER_TOKEN=${TWITTER_TOKEN}
            - SUB_TOKEN=${SUB_TOKEN}
            - WEBHOOK=${PROXIMA_MEME}
            - QUERY_STR=${MEME_QUERY}
    
    proxima_schedule:
        image: proxima_twitter
        container_name: proxima_schedule
        restart: always
        environment: 
            - TWITTER_TOKEN=${TWITTER_TOKEN}
            - SUB_TOKEN=${SUB_TOKEN}
            - WEBHOOK=${PROXIMA_SCHEDULE}
            - QUERY_STR=${SCHEDULE_QUERY}