version: '3'
services:
    app:
        build: image/
        image: ks_mini2
        container_name: ks_mini2
        restart: unless-stopped
        environment:
            - API_KEY=${API_KEY}
            - MONGODB=${MONGODB}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}