FROM python:3.10.5-slim

WORKDIR /app

RUN pip install requests \
	&& pip install bs4 \
	&& pip install html5lib

RUN apt-get update -y \
    && apt-get install -y tzdata

ENV TZ=Asia/Taipei

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata 

COPY miniexpress_dlc.py app.py

CMD ["python", "-u", "app.py"]